<?php
define('NOMBRE_SERVIDOR','localhost');
define('NOMBRE_USUARIO','root');
define('PASSWORD','');
define('NOMBRE_BD','unAventon');

define("SERVIDOR", "http://localhost/unAventon");
define("RUTA_REGISTRO",SERVIDOR."/registro.php");
define("RUTA_REGISTRO_CORRECTO",SERVIDOR."/registro-correcto.php");
define("RUTA_LOGIN",SERVIDOR."/login2.php");
define("RUTA_CSS", SERVIDOR . "/css/" );
define("RUTA_JS", SERVIDOR . "/js/" );
define("RUTA_LOGOUT",SERVIDOR ."/logout.php");
define("RUTA_PERFIL",SERVIDOR."/perfil.php");
define("RUTA_EDITOR_PERFIL",SERVIDOR."/editor-perfil.php");
define("RUTA_INTRODUCCION_CONTRASEÑA",SERVIDOR."/introduccion-contraseña.php");
define("RUTA_EDITOR_CONTRASEÑA",SERVIDOR."/editor-contraseña.php");
define("RUTA_ELIMINAR_CUENTA",SERVIDOR."/eliminarCuenta.inc.php");
define("RUTA_INGRESO_PATENTE",SERVIDOR."/ingreso-patente.php");
define("RUTA_AUTO_EXISTE",SERVIDOR."/auto-existe.php");
define("RUTA_AUTO_NUEVO",SERVIDOR."/auto-nuevo.php");
define("RUTA_EDITOR_AUTO",SERVIDOR."/editor-auto.php");
define("RUTA_ELIMINAR_AUTO",SERVIDOR."/eliminarAuto.inc.php");
define("RUTA_MOSTRAR_AUTO",SERVIDOR."/mostrar-auto.php");
define("RUTA_SELECCION_TIPO_VIAJE",SERVIDOR."/seleccion-tipo-viaje.php");
define("RUTA_CREAR_VIAJE_UNICO",SERVIDOR."/crear-viaje-unico.php");
define("RUTA_CREAR_VIAJE_MULTIPLE",SERVIDOR."/crear-viaje-multiple.php");
define("RUTA_AGREGAR_FECHA",SERVIDOR."/agregar-fecha.php");
define("RUTA_MOSTRAR_PROCESO_VIAJE_MULTIPLE",SERVIDOR."/mostrar-proceso-viaje-multiple.inc.php");
define("RUTA_DETALLE_VIAJE",SERVIDOR."/detalle-viaje.php");
define("RUTA_MOSTRAR_PERFIL",SERVIDOR."/mostrar-perfil.php");
define("RUTA_MOSTRAR_POSTULANTES",SERVIDOR."/mostrar-postulantes.php");
define("RUTA_MOSTRAR_NOTIFICACIONES",SERVIDOR."/mostrar-notificaciones.php");
define("RUTA_MOSTRAR_ACEPTADOS",SERVIDOR."/mostrar-aceptados.php");
define("RUTA_PAGOS_PENDIENTES",SERVIDOR."/pagosPendientes.php");
define("RUTA_CALIFICACIONES_PENDIENTES",SERVIDOR."/calificaciones-pendientes.php");
define("RUTA_VER_MIS_CALIFICACIONES",SERVIDOR."/ver-mis-calificaciones.php");
define("RUTA_INGRESO_TARJETA",SERVIDOR."/ingreso-tarjeta.php");